### ISSUE TITLE
스테이징, 커밋, 푸쉬 취소하는 것도 넣어주세요! ((광광

### ISSUE THREAD

**Issue by sunrabbit123** [siwony/Organize-Git-command#3]
작업하다보면 실수로 커밋을 잘못하거나, 스테이징을 잘못하는 경우도 생기게 되는데 
이에 대한 부분도 같이 넣어줬으면 좋겠습니다

**Comment by siwony** [comment]
곧 내용을 추가할것입니다! 다시한번 상기시켜주셔서 감사합니다 😀
